drop table app_language cascade constraints;
drop table app_language_l10n cascade constraints;
drop table app_permission cascade constraints;
drop table app_permission_l10n cascade constraints;
drop table app_role cascade constraints;
drop table app_role_l10n cascade constraints;
drop table app_role_permissions cascade constraints;
drop table app_user cascade constraints;
drop table app_user_roles cascade constraints;
drop table attribute_status cascade constraints;
drop table attribute_status_l10n cascade constraints;
drop table attribute_status_transition cascade constraints;
drop table attribute_status_transition_l10n cascade constraints;
drop table attribute_type cascade constraints;
drop table attribute_type_l10n cascade constraints;
drop table attribute_type_setup cascade constraints;
drop table contact cascade constraints;
drop table gender cascade constraints;
drop table gender_l10n cascade constraints;
drop table race_event cascade constraints;
drop table race_event_status cascade constraints;
drop table race_event_status_l10n cascade constraints;
drop table race_event_status_transition cascade constraints;
drop table race_event_status_transition_l10n cascade constraints;
drop sequence app_language_l10n_seq;
drop sequence attribute_status_l10n_seq;
drop sequence attribute_status_transition_l10n_seq;
drop sequence attribute_type_l10n_seq;
drop sequence contact_seq;
drop sequence gender_l10n_seq;
drop sequence permission_l10n_seq;
drop sequence race_event_status_l10n_seq;
drop sequence race_event_status_transition_l10n_seq;
drop sequence race_event_seq;
drop sequence role_l10n_seq;
drop sequence user_seq;
