alter table app_language drop foreign key FKh0s9dhkbqebj5ylqroe5d2iix;
alter table app_language drop foreign key FKj8ybyfqwdxd18pl7ie5sku275;
alter table app_language drop foreign key FKk4wlk885an7gbtpjljjjrfi3p;
alter table app_language drop foreign key FKcrfolfp61bj6wlo8y6wtojep4;
alter table app_language_l10n drop foreign key FK7ajcd24gaqrvepcd8thqiursc;
alter table app_language_l10n drop foreign key FKkevs1xxgnfs3xy2r0lp933ye5;
alter table app_language_l10n drop foreign key FKbd8a1nv1fcxuquwvxsarm8q08;
alter table app_permission drop foreign key FKbt2v0roscpvg6e9pnj3aydsqr;
alter table app_permission drop foreign key FK6q1l4xjxv1p40jeku1r43thkf;
alter table app_permission drop foreign key FKp2opcwtp8j2253jw25flaqvai;
alter table app_permission drop foreign key FK6mnlatrpcobombmm2ooqqwhom;
alter table app_permission_l10n drop foreign key FKg0ughyqpci790bqhdq2058wix;
alter table app_permission_l10n drop foreign key FK6ydp4n4d1hvs13640frjacoox;
alter table app_permission_l10n drop foreign key FKkt6g7tb7xnh37c8aqhc3o5a67;
alter table app_role drop foreign key FK94gccxdqxrncpe40caf7vwf8y;
alter table app_role drop foreign key FKpjeyrdvlmq8x6fo0uhhvbau4x;
alter table app_role drop foreign key FKg29868ulsfko0eenf4om576f7;
alter table app_role drop foreign key FKgh1wvr23wmqlb4qs609qcq1xn;
alter table app_role_l10n drop foreign key FKmgvow11xhn2og2ktseixyppk6;
alter table app_role_l10n drop foreign key FKmt99b8uxbwlweq11xo73sjuyu;
alter table app_role_l10n drop foreign key FKe6yxvepjurmholt30ax2t3090;
alter table app_role_permissions drop foreign key FKhj9btn1giylub8xpf22y1s1yj;
alter table app_role_permissions drop foreign key FK5ejh9hrq3wlrgqvxxv9eq0g8g;
alter table app_user drop foreign key FKlkv4hvh7geqc0f4iessohwnwd;
alter table app_user drop foreign key FKlqd19spd436qxo0ic3v7klhwh;
alter table app_user drop foreign key FKee6nreu2puabqwda2a9d0vp8y;
alter table app_user_roles drop foreign key FKoakt07mc9x8g42934jlh183n7;
alter table app_user_roles drop foreign key FK3lwiahkol5aetc57pto5olacf;
alter table attribute_status drop foreign key FKno6ohoqdoq779y2k98s0yli1;
alter table attribute_status drop foreign key FKbc05jo4suq09m47n28s5nq4gi;
alter table attribute_status drop foreign key FKl5g2o3q6ypr1c91r3fmiq517o;
alter table attribute_status drop foreign key FK4eq7v7t400vvdoy6re1imnhm9;
alter table attribute_status_l10n drop foreign key FKtm4h8fclvd5rvgb2qc4nfvm82;
alter table attribute_status_l10n drop foreign key FKlxpxobkusen977lvydfa6tsdx;
alter table attribute_status_l10n drop foreign key FKomhrl3jj20516t2yj7hb78da;
alter table attribute_status_transition drop foreign key FK2sdcp4scue5w7oimkakknyulr;
alter table attribute_status_transition drop foreign key FKg0xkhqfsfcnd18b5byxawp7t1;
alter table attribute_status_transition drop foreign key FKlphp1obx8mhiv42iyn91qt6e1;
alter table attribute_status_transition_l10n drop foreign key FKlaiyepqgc7wfm3jx5i2mb4cgp;
alter table attribute_status_transition_l10n drop foreign key FKqiaad40hmcq6328t2alj2j4ww;
alter table attribute_status_transition_l10n drop foreign key FKa9ajtfmanp81iksfdv7aooq0f;
alter table attribute_type drop foreign key FKudsr0sn6o848eesypx64xqd1;
alter table attribute_type drop foreign key FKnyttgeh9fk2tmh714c23i2kai;
alter table attribute_type_l10n drop foreign key FK7y78uuuuf9cl7pc9notolq994;
alter table attribute_type_l10n drop foreign key FK3s14qkv6xk34bcw1p8avy2g93;
alter table attribute_type_l10n drop foreign key FKsm0m4k19huin7bbx1vb965x5t;
alter table attribute_type_setup drop foreign key FKca0qk5gkhf80vgfiejvr4l1se;
alter table attribute_type_setup drop foreign key FKd8u0aqy74f5wlmm3eiqapl4xc;
alter table contact drop foreign key FK14cmp9be36agr8bk0yr1cyf4h;
alter table contact drop foreign key FKdoetcflog2qbwm0m10fj5ncxa;
alter table contact drop foreign key FK13pbh9fyrlx893xitm053qmrr;
alter table gender drop foreign key FK8pki0sk3ife2hmfq8159nr2m1;
alter table gender drop foreign key FKmil9olifwoneara4dqd8775k7;
alter table gender drop foreign key FKe5j90esps2ywt9x24p2h00wqw;
alter table gender drop foreign key FK6xnrvfr7fjow3ggwbjw42a7sm;
alter table gender_l10n drop foreign key FKc1urc6udo3bphugdxjhelbog7;
alter table gender_l10n drop foreign key FKqsiyigt94vu0lt9c3gr798h14;
alter table gender_l10n drop foreign key FKn6tws0y5sp4ubh4fuv7glvki7;
alter table race_event drop foreign key FKov3x4r2cgt8nqnlsgsquongco;
alter table race_event drop foreign key FKsubsgjy4pk2ap566a4my19ox1;
alter table race_event drop foreign key FKnmc62hlldddmjcw42pc28qn4o;
alter table race_event_status drop foreign key FKb5evvqd2iqh9y292vthqd4brr;
alter table race_event_status drop foreign key FKsx941sfgq2wi1lvehstnfdht8;
alter table race_event_status drop foreign key FK9hpmd8inf4dgbf4yx422h1mwu;
alter table race_event_status drop foreign key FKk4y89afdsypb3vjb7lshdmxdg;
alter table race_event_status_l10n drop foreign key FK99ulw7tl5b4aof9htkjgn2j10;
alter table race_event_status_l10n drop foreign key FKe7hgnsg9act5feo3x74vjgra4;
alter table race_event_status_l10n drop foreign key FK4ahlers6yqpxjqbkudm23h6hh;
alter table race_event_status_transition drop foreign key FK9682qqgov2iily16uo5cbhlo2;
alter table race_event_status_transition drop foreign key FKm21c6y6f9vqnf4ltjpg8k55dd;
alter table race_event_status_transition drop foreign key FKdrpkgw0l8la73ex5l2nsb55bm;
alter table race_event_status_transition_l10n drop foreign key FK5do7l0ncd70him6a8gpcbj0mg;
alter table race_event_status_transition_l10n drop foreign key FKhxggber7u4fbq32ix871r1i61;
alter table race_event_status_transition_l10n drop foreign key FK2ha2oypw3aa146nkgsyyw0d2f;
drop table if exists app_language;
drop table if exists app_language_l10n;
drop table if exists app_permission;
drop table if exists app_permission_l10n;
drop table if exists app_role;
drop table if exists app_role_l10n;
drop table if exists app_role_permissions;
drop table if exists app_user;
drop table if exists app_user_roles;
drop table if exists app_language_l10n_seq;
drop table if exists attribute_status;
drop table if exists attribute_status_l10n;
drop table if exists attribute_status_transition;
drop table if exists attribute_status_transition_l10n;
drop table if exists attribute_type;
drop table if exists attribute_type_l10n;
drop table if exists attribute_type_setup;
drop table if exists attribute_status_l10n_seq;
drop table if exists attribute_status_transition_l10n_seq;
drop table if exists attribute_type_l10n_seq;
drop table if exists contact;
drop table if exists contact_seq;
drop table if exists gender;
drop table if exists gender_l10n_seq;
drop table if exists gender_l10n;
drop table if exists permission_l10n_seq;
drop table if exists race_event;
drop table if exists race_event_status;
drop table if exists race_event_status_l10n;
drop table if exists race_event_status_transition;
drop table if exists race_event_status_transition_l10n;
drop table if exists race_event_status_l10n_seq;
drop table if exists race_event_status_transition_l10n_seq;
drop table if exists race_event_seq;
drop table if exists role_l10n_seq;
drop table if exists user_seq;
